Vagrant.configure(2) do |config|
	config.vm.define "jenkins-slave" do |node|
		node.vm.box = "ubuntu/bionic64"
		node.vm.box_check_update = false
    	node.vm.network "private_network", ip: "192.168.5.51"
    	node.vm.hostname = "jenkins-slave"
      	node.vm.provision "install-packages", type: "shell", :path => "scripts/install.sh"
      	node.vm.provision "setup-dns", type: "shell", :path => "scripts/update-dns.sh"
    	node.vm.provider "virtualbox" do |v|
    		v.name = "jenkins-slave"
    		v.memory = 2048
    		v.cpus = 2
    	end
	end
end
